extends GutTest
## Tests for Wisp enemy state logic and transitions.
## Uses lightweight stubs — no scene instancing required.

var config: GameConfig


func before_each() -> void:
	config = GameConfig.new()


# ── Patrol ────────────────────────────────────────────────────────────────

func test_patrol_stays_within_radius() -> void:
	# Verify that a random point generated by patrol stays within the radius.
	# We replicate the patrol target-picking math 100 times.
	var spawn := Vector3.ZERO
	var radius: float = config.wisp_patrol_radius
	var all_within := true
	for i in 100:
		var angle: float = randf() * TAU
		var r: float = randf() * radius
		var target := spawn + Vector3(cos(angle) * r, 0.0, sin(angle) * r)
		var flat_dist: float = Vector2(target.x, target.z).length()
		if flat_dist > radius + 0.001:
			all_within = false
			break
	assert_true(all_within,
		"All patrol waypoints should be within wisp_patrol_radius of spawn")


func test_aggro_range_default_positive() -> void:
	assert_gt(config.wisp_aggro_range, 0.0,
		"wisp_aggro_range should be positive")


func test_patrol_to_chase_distance_threshold() -> void:
	# Aggro triggers when distance <= wisp_aggro_range.
	var player_dist: float = config.wisp_aggro_range - 0.5
	assert_true(player_dist <= config.wisp_aggro_range,
		"Player inside aggro range should trigger Chase")


# ── Chase ─────────────────────────────────────────────────────────────────

func test_chase_to_windup_distance_threshold() -> void:
	var player_dist: float = config.wisp_attack_range - 0.1
	assert_true(player_dist <= config.wisp_attack_range,
		"Player inside attack range should trigger WindUp")


func test_chase_returns_to_patrol_hysteresis() -> void:
	# Chase only returns to Patrol when distance > aggro_range * 1.5.
	var hysteresis_dist: float = config.wisp_aggro_range * 1.5 + 0.1
	assert_true(hysteresis_dist > config.wisp_aggro_range * 1.5,
		"Player beyond hysteresis threshold should return to Patrol")


func test_hysteresis_prevents_flicker() -> void:
	# A player at exactly aggro_range should NOT return to Patrol from Chase.
	var player_dist: float = config.wisp_aggro_range
	var should_return: bool = player_dist > config.wisp_aggro_range * 1.5
	assert_false(should_return,
		"Player at exact aggro_range should not trigger Patrol return (hysteresis)")


# ── WindUp ────────────────────────────────────────────────────────────────

func test_windup_duration_positive() -> void:
	assert_gt(config.wisp_windup_duration, 0.0,
		"wisp_windup_duration should be positive")


func test_windup_transitions_to_attack_after_duration() -> void:
	# Simulate timer expiry.
	var timer: float = config.wisp_windup_duration
	var dt: float = 1.0 / 60.0
	var frames: int = ceili(config.wisp_windup_duration / dt) + 1
	for i in frames:
		timer -= dt
	assert_true(timer <= 0.0,
		"WindUp timer should expire after wisp_windup_duration seconds")


func test_windup_interrupted_by_on_damaged() -> void:
	# Replicate the interrupted flag logic from WispWindUp.
	var interrupted: bool = false
	# Simulate on_damaged() being called.
	interrupted = true
	assert_true(interrupted,
		"WindUp should set interrupted flag when on_damaged() is called")


# ── Attack ────────────────────────────────────────────────────────────────

func test_attack_active_frames_positive() -> void:
	assert_gt(config.wisp_attack_active_frames, 0,
		"wisp_attack_active_frames should be positive")


func test_attack_frames_count_down_to_zero() -> void:
	var frames: int = config.wisp_attack_active_frames
	for i in config.wisp_attack_active_frames:
		frames -= 1
	assert_eq(frames, 0,
		"Attack frame counter should reach zero after active frames elapse")


# ── Stagger ───────────────────────────────────────────────────────────────

func test_stagger_duration_positive() -> void:
	assert_gt(config.wisp_stagger_duration, 0.0,
		"wisp_stagger_duration should be positive")


func test_stagger_returns_to_chase_after_duration() -> void:
	var timer: float = config.wisp_stagger_duration
	var dt: float = 1.0 / 60.0
	var frames: int = ceili(config.wisp_stagger_duration / dt) + 1
	for i in frames:
		timer -= dt
	assert_true(timer <= 0.0,
		"Stagger timer should expire after wisp_stagger_duration seconds")


# ── Death / XPOrb ─────────────────────────────────────────────────────────

func test_xp_reward_matches_config() -> void:
	assert_eq(config.wisp_xp_reward, 20,
		"wisp_xp_reward should match the default config value")


func test_enemy_stats_built_from_config() -> void:
	var stats := EnemyStats.new()
	stats.max_health = config.wisp_max_health
	stats.current_health = config.wisp_max_health
	stats.xp_reward = config.wisp_xp_reward
	assert_eq(stats.max_health, config.wisp_max_health,
		"EnemyStats built from config should have correct max_health")
	assert_eq(stats.xp_reward, config.wisp_xp_reward,
		"EnemyStats built from config should have correct xp_reward")


# ── Float height ──────────────────────────────────────────────────────────

func test_float_height_positive() -> void:
	assert_gt(config.wisp_float_height, 0.0,
		"wisp_float_height should be positive")


func test_float_correction_moves_toward_target() -> void:
	# Simulate one frame of float spring correction.
	var spawn_y: float = 0.0
	var current_y: float = 0.0
	var target_y: float = spawn_y + config.wisp_float_height
	var delta: float = 1.0 / 60.0
	var vel_y: float = (target_y - current_y) * 8.0 * delta * 60.0
	var new_y: float = current_y + vel_y * delta
	assert_true(new_y > current_y,
		"Float spring should move the Wisp upward toward target height")
